import os
import random
from datetime import datetime, timedelta

def generate_office_files(directory):
    print("Generating Office files...")
    try:
        import openpyxl
        # Generate XLSX
        print("Generating XLSX...")
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Sales Data"
        ws.append(["Date", "Product", "Quantity", "Price", "Total"])
        products = ["Laptop", "Mouse", "Keyboard", "Monitor", "Desk"]
        for i in range(1, 21):
            date_str = (datetime.now() - timedelta(days=i)).strftime('%Y-%m-%d')
            prod = random.choice(products)
            qty = random.randint(1, 10)
            price = random.randint(20, 1000)
            ws.append([date_str, prod, qty, price, qty * price])
        wb.save(os.path.join(directory, "sales_report.xlsx"))
        
        # Second XLSX
        wb2 = openpyxl.Workbook()
        ws2 = wb2.active
        ws2.title = "Inventory"
        ws2.append(["Item ID", "Name", "Stock", "Location"])
        for i in range(1, 11):
            ws2.append([f"ITM-{1000+i}", f"Component {i}", random.randint(0, 500), random.choice(["Warehouse A", "Warehouse B"])])
        wb2.save(os.path.join(directory, "inventory.xlsx"))

    except ImportError:
        print("openpyxl is not installed. Skipping XLSX generation.")

    try:
        from docx import Document
        # Generate DOCX
        print("Generating DOCX...")
        for i in range(1, 4):
            doc = Document()
            doc.add_heading(f'Confidential Report {i}', 0)
            doc.add_paragraph('This is a dummy document generated for RPA testing purposes.')
            doc.add_heading('Summary', level=1)
            doc.add_paragraph(f'This report was generated on {datetime.now().strftime("%Y-%m-%d")}. The system observed a 15% increase in efficiency during the last quarter.')
            doc.add_heading('Action Items', level=1)
            doc.add_paragraph('1. Review automation logs', style='List Number')
            doc.add_paragraph('2. Update credentials', style='List Number')
            doc.add_paragraph('3. Restart bot agent', style='List Number')
            doc.save(os.path.join(directory, f"report_{i}.docx"))
    except ImportError:
        print("python-docx is not installed. Skipping DOCX generation.")

    try:
        from pptx import Presentation
        # Generate PPTX
        print("Generating PPTX...")
        prs = Presentation()
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = "Quarterly Business Review"
        subtitle.text = "Generated by Automation"
        
        bullet_slide_layout = prs.slide_layouts[1]
        slide2 = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide2.shapes
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        title_shape.text = "Key Metrics"
        tf = body_shape.text_frame
        tf.text = "Revenue: $1.2M"
        p = tf.add_paragraph()
        p.text = "Costs: $0.8M"
        p.level = 1
        p2 = tf.add_paragraph()
        p2.text = "Profit: $0.4M"
        p2.level = 1
        
        prs.save(os.path.join(directory, "presentation.pptx"))
    except ImportError:
        print("python-pptx is not installed. Skipping PPTX generation.")

if __name__ == "__main__":
    target_dir = r"c:\Users\amray\Downloads\Dummy Files"
    os.makedirs(target_dir, exist_ok=True)
    generate_office_files(target_dir)
    print("Done!")
